from backend.db.schema.gbif_observations import GBIF_OBSERVATIONS_TABLE
from backend.db.schema.tx_taxa import TX_TAXA_TABLE
from psycopg import sql

DWC_OCCURRENCE_SELECT_CLAUSE = sql.SQL('''
    SELECT
        gbif_id AS "gbifID",
        access_rights AS "accessRights",
        license,
        modified,
        publisher,
        "references",
        rights_holder AS "rightsHolder",
        recorded_by AS "recordedBy",
        dataset_id AS "datasetID",
        institution_code AS "institutionCode",
        dataset_name AS "datasetName",
        information_withheld AS "informationWithheld",
        occurrence_id AS "occurrenceID",
        individual_count AS "individualCount",
        event_date AS "eventDate",
        event_time AS "eventTime",
        year,
        month,
        day,
        verbatim_event_date AS "verbatimEventDate",
        field_notes AS "fieldNotes",
        event_remarks AS "eventRemarks",
        country_code AS "countryCode",
        state_province AS "stateProvince",
        county,
        locality,
        verbatim_locality AS "verbatimLocality",
        decimal_latitude AS "decimalLatitude",
        decimal_longitude AS "decimalLongitude",
        coordinate_uncertainty_in_meters AS "coordinateUncertaintyInMeters",
        coordinate_precision AS "coordinatePrecision",
        scientific_name AS "scientificName",
        kingdom,
        phylum,
        class,
        "order",
        family,
        genus,
        species,
        subspecies,
        taxon_rank AS "taxonRank",
        taxonomic_status AS "taxonomicStatus",
        dataset_key AS "datasetKey",
        last_interpreted AS "lastInterpreted",
        issue,
        taxon_key,
        accepted_taxon_key AS "acceptedTaxonKey",
        accepted_scientific_name AS "acceptedScientificName",
        verbatim_scientific_name AS "verbatimScientificName",
        collection_start_date as "collectionStartDate",
        collection_end_date as "collectionEndDate"
    FROM {gbif_table}
''').format(gbif_table=sql.Identifier(GBIF_OBSERVATIONS_TABLE.name))

DWC_TAXA_SELECT_CLAUSE = sql.SQL('''
    SELECT
        taxon_id AS "taxonID",
        dataset_id AS "datasetID",
        parent_name_usage_id AS "parentName",
        accepted_name_usage_id AS "acceptedNameUsageID",
        original_name_usage_id AS "originalNameUsageID",
        scientific_name AS "scientificName",
        scientific_name_authorship AS "scientificNameAuthorship",
        canonical_name AS "canonicalName",
        generic_name AS "genericName",
        taxon_rank AS "taxonRank",
        name_published_in AS "namePublishedIn",
        taxonomic_status AS "taxonomicStatus",
        taxon_remarks AS "taxonRemarks",
        kingdom,
        phylum,
        class,
        "order",
        family,
        genus,
        species,
        subspecies,
        ns_rank_state AS "rankState",
        ns_rank_state_no_inat AS "rankStateNoINat",
        us_invasive AS "uSInvasive"
    FROM {backbone}            
''').format(backbone=sql.Identifier(TX_TAXA_TABLE.name))
