pid       temp/nginx.pid;

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log    logs/access.log;
    error_log     logs/error.log;
    client_body_temp_path temp/client_body_temp;

    sendfile on;

    server {
        listen       443;
        server_name  https://txinverts.tacc.utexas.edu;

        root   /srv/tx_inverts/frontend/dist;
        index  index.html;

        # Frontend (Svelte SPA)
        location / {
            try_files $uri $uri/ /index.html;
        }

        location /server/ {
            proxy_pass http://127.0.0.1:8000/;
        }

        # Catch exact /server with no slash
        location = /server {
            proxy_pass http://127.0.0.1:8000/;
        }
    }
}