[pytest]
asyncio_mode = auto
# By default, don't run tests that require external API connection
addopts = -m 'not requires_external_api'
markers =
    requires_external_api: marks test as needing external api (internet connection)
    db: marks test as needing local PostgreSQL connection