# Taxa-related constants
from typing import List, Literal

type TaxonomicRank = Literal[
    'kingdom',
    'phylum',
    'subphylum',
    'superclass',
    'class',
    'subclass',
    'infraclass',
    'subterclass',
    'superorder',
    'order',
    'suborder',
    'infraorder',
    'parvorder',
    'nanorder',
    'section zoology',
    'subsection zoology',
    'superfamily',
    'epifamily',
    'series zoology',
    'family',
    'subfamily',
    'supertribe',
    'tribe',
    'subtribe',
    'infratribe',
    'genus',
    'subgenus',
    'species',
    'subspecies',
    'variety',
    'form'
]

TAXON_RANK_ORDER: List[TaxonomicRank] = [
    'kingdom',
    'phylum',
    'subphylum',
    'superclass',
    'class',
    'subclass',
    'infraclass',
    'subterclass',
    'superorder',
    'order',
    'suborder',
    'infraorder',
    'parvorder',
    'nanorder',
    'section zoology',
    'subsection zoology',
    'superfamily',
    'epifamily',
    'series zoology',
    'family',
    'subfamily',
    'supertribe',
    'tribe',
    'subtribe',
    'infratribe',
    'genus',
    'subgenus',
    'species',
    'subspecies',
    'variety',
    'form',
]
