# Taxa-related constants
from typing import Literal

TAXON_RANK_ORDER = [
    'kingdom',
    'phylum',
    'subphylum',
    'superclass',
    'class',
    'subclass',
    'infraclass',
    'subterclass',
    'superorder',
    'order',
    'suborder',
    'infraorder',
    'parvorder',
    'nanorder',
    'section zoology',
    'subsection zoology',
    'superfamily',
    'epifamily',
    'series zoology',
    'family',
    'subfamily',
    'supertribe',
    'tribe',
    'subtribe',
    'infratribe',
    'genus',
    'subgenus',
    'species',
    'subspecies',
    'infraspecific_name',
    'variety',
    'form',
]

# Including only KEYED columns in DWCA
KEYED_TAXON_RANK_ORDER = [
    'kingdom',
    'phylum',
    'class',
    'order',
    'superfamily',
    'family',
    'subfamily',
    'tribe',
    'subtribe',
    'genus',
    'subgenus',
    'species',
]

type TaxonomicRank = Literal[
    'kingdom',
    'phylum',
    'subphylum',
    'class',
    'subclass',
    'superorder',
    'order',
    'suborder',
    'infraorder',
    'superfamily',
    'family',
    'subfamily',
    'tribe',
    'subtribe',
    'genus',
    'subgenus',
    'species',
    'subspecies',
    'infraspecific_name',
    'variety',
    'form',
]

RANK_COLS = [f'{r}_key' for r in KEYED_TAXON_RANK_ORDER]
