name: Python Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install system dependencies
              run: |
                  sudo apt-get update 
                  sudo apt-get install -y --fix-missing gdal-bin libgdal-dev libpq-dev

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.13.2'

            - run: pip install -r ./backend/github_requirements.txt
            - run: pytest ./backend
              env:
                  # GLOBAL APP
                  ENV: ${{secrets.ENV}}
                  GBIF__USER: ${{secrets.GBIF__USER}}
                  GBIF__EMAIL: ${{secrets.GBIF__EMAIL}}
                  GBIF__PASSWORD: ${{secrets.GBIF__PASSWORD}}

                  # PostgreSQL
                  DATABASE__USER: ${{secrets.DATABASE__USER}}
                  DATABASE__PASSWORD: ${{secrets.DATABASE__PASSWORD}}
                  DATABASE__HOST: ${{secrets.DATABASE__HOST}}
                  DATABASE__PORT: ${{secrets.DATABASE__PORT}}
                  DATABASE__NAME: ${{secrets.DATABASE__NAME}}

                  # CORS
                  CORS__DOMAIN: ${{secrets.CORS__DOMAIN}}
