name: Python Tests

on: [push, pull_request]

jobs:
    test-python:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgis/postgis:16-3.4
                env:
                    POSTGRES_USER: test_user
                    POSTGRES_PASSWORD: test_pass
                    POSTGRES_DB: test_inverts
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U test_user"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

        environment: TESTING

        steps:
            - uses: actions/checkout@v3
            - name: Enable PostGIS
              run: psql -U test_user -h localhost -d test_inverts -c "CREATE EXTENSION IF NOT EXISTS postgis;"
              env:
                  PGPASSWORD: test_pass
            - name: Install system dependencies
              run: |
                  sudo apt-get update 
                  sudo apt-get install -y --fix-missing gdal-bin libgdal-dev libpq-dev

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.13.2'

            - run: pip install -r ./backend/github_requirements.txt
            - run: pytest ./backend
              env:
                  # GLOBAL APP
                  ENV: ${{secrets.ENV}}
                  GBIF__USER: ${{secrets.GBIF__USER}}
                  GBIF__EMAIL: ${{secrets.GBIF__EMAIL}}
                  GBIF__PASSWORD: ${{secrets.GBIF__PASSWORD}}

                  # PostgreSQL
                  DATABASE__USER: ${{secrets.DATABASE__USER}}
                  DATABASE__PASSWORD: ${{secrets.DATABASE__PASSWORD}}
                  DATABASE__HOST: ${{secrets.DATABASE__HOST}}
                  DATABASE__PORT: ${{secrets.DATABASE__PORT}}
                  DATABASE__NAME: ${{secrets.DATABASE__NAME}}

                  # CORS
                  CORS__DOMAIN: ${{secrets.CORS__DOMAIN}}
    test-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - run: npm ci
              working-directory: ./frontend
            - run: npm run vitest
              working-directory: ./frontend
